### ISSUE TITLE
Issue with compilation of libspatialite against libproj

### ISSUE THREAD

**Issue by thibaultduponchelle** [shawnlaffan/perl-alien-spatialite#1]
Hello,

First thank you a lot for these Alien:: packages ! :smile: 

I'm trying to install Alien::spatialite but I have some compilation issues.

All deps are building fine, it's only Alien::spatialite.

I can demonstrate them with CI builds : 
See for instance https://github.com/thibaultduponchelle/messy-perl-ci-workflows/runs/626528384?check_suite_focus=true which is produced by https://github.com/thibaultduponchelle/messy-perl-ci-workflows/blob/master/.github/workflows/spatialite.yml

When I check why, I have a pkg-config problem between libspatialite and libproj : 
```
2020-04-28T10:12:02.9977487Z 2020-04-28T10:11:57,2749,Alien-spatialite-1.04| checking proj_api.h usability... no
2020-04-28T10:12:02.9977847Z 2020-04-28T10:11:57,2749,Alien-spatialite-1.04| checking proj_api.h presence... no
2020-04-28T10:12:02.9978214Z 2020-04-28T10:11:57,2749,Alien-spatialite-1.04| checking for proj_api.h... no
```

I'm totally newcomer to Alien::Build and I guess it's something related to PkgConfig plugin and the way *Alien::proj* exposes libs and cflags to *Alien::spatialite*
Or related to the plugin SearchDep ? 

I have the error on github ci but also on my computer. And I see well the pkg-config file and the headers installed on my computer after *Alien::proj* install.

I also copied your repository to check the travis build and I reproduce the error with you travis.yml : 
Your travis build is OK : https://travis-ci.org/github/shawnlaffan/perl-alien-spatialite/jobs/475863447
My travis build is KO : https://travis-ci.org/github/thibaultduponchelle/tib-spatialite/jobs/680539399

And the logs : 
```
checking proj_api.h usability... no
checking proj_api.h presence... no
checking for proj_api.h... no
configure: error: cannot find proj_api.h, bailing out
Alien::Build::Plugin::Cleanse::BuildDir> Going to delete /home/travis/build/thibaultduponchelle/tib-spatialite/_alien/build_Hyjp/libspatialite-4.3.0a
Alien::Build::Plugin::Cleanse::BuildDir> Currently in /home/travis/build/thibaultduponchelle/tib-spatialite/_alien/build_Hyjp/libspatialite-4.3.0a
Alien::Build::Plugin::Cleanse::BuildDir> Going to parent of build directory
Alien::Build::Plugin::Cleanse::BuildDir> Deleted 4888 items
nothing was installed into destdir at /home/travis/perl_modules/lib/perl5/Alien/Build/Plugin/Core/Gather.pm line 77.
Makefile:1048: recipe for target '_alien/mm/build' failed
make: *** [_alien/mm/build] Error 2
The command "make" exited with 2.
```

You can check that I really copy pasted your repo to create this failing travis run : https://github.com/thibaultduponchelle/tib-spatialite 

I tried to play with Alien::Build versions or Alien::proj version (play = downgrade) but currently I have no solution.

Do you have an idea about what is wrong ? Am I doing something wrong ?

Could you please trigger a new build of this repository to see if you have the issue ? 

Thank you a lot.

Best regards.

Thibault

**Comment by shawnlaffan** [comment]
Thanks for the report.  

The alien processes are working.  

The issue is due Proj version 6 removing proj_api.h from its header files.  Spatialite has [been updated to work with Proj 6+](https://www.gaia-gis.it/fossil/libspatialite/tktview?name=6eabdf0e6d) but a new version has not yet been released.  

An interim solution if you do need spatialite is to force Alien::proj to install version 5 or 4.  I'll see if I can add it as an option via en environment variable, but if you need it sooner then you can patch the Alien::proj alienfile download code.  

https://github.com/shawnlaffan/perl-alien-proj/blob/4310bf84c4b9bf9a7f6f2c45e8fe3af8663ebb4c/alienfile#L48-L51

Note that if you also use Alien::gdal as a share install then it will need to be recompiled as GDAL 3 needs Proj 6+.  Alien::gdal will drop to GDAL version 2 if proj 4 or 5 is found.

**Comment by thibaultduponchelle** [comment]
Great thank you a lot for the details. 

Everything is clear now. 

Waiting for spatialite update is probably better than forbidding temporarily Proj 6 I guess.

**Comment by shawnlaffan** [comment]
Yes, if spatialite is not essential then it's probably better to skip it for now.
